name: Public Npm

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish npm'
    environment: npm

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: actions/checkout@master
      - name: Install and Build 
        run: |
          npm run installall
          npm run lib

      - name: 'Publish to the npm registry'
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          default_branch: 'master'