name: Public Npm

# 当push到deploy分支时触发
on:
  push:
    branches: [ deploy ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3


    # 使用 nodejs 的版本
    - name: Use Node.js v16.11.0
      uses: actions/setup-node@v3
      with:
        node-version: v16.11.0

    # 安装依赖
    - name: Install
      run: npm i --registry=http://registry.npmmirror.com

    # 打包
    - name: Build
      run: npm run lib

    # 发布
    - name: Publish
      uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ secrets.NPM_TOKEN }}
